language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davidchow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run davidchow/react-test npm run test

after_success:
  - docker build -t davidchow/complex-client ./client
  - docker build -t davidchow/complex-api ./api
  - docker build -t davidchow/complex-nginx ./nginx
  - docker build -t davidchow/complex-worker ./worker
  - echo $DOCKER_ID
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push davidchow/complex-client
  - docker push davidchow/complex-api
  - docker push davidchow/complex-nginx
  - docker push davidchow/complex-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'complex-docker'
  env: 'Complexdocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-674117693681'
  bucket_path: 'complex-docker'
  on:
    branch: main
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY